declare const console: {
    log(data: any);
};

declare type WindowID = number;
declare type Slot = number;

declare type Entity = {
    RuntimeID: number
    UniqueID: number
    EntityType: string

    Position: [number, number, number];
    Pitch: number;
    Yaw: number;
    Velocity: [number, number, number];
}

declare type ItemInstance = {
    StackNetworkID: number;
    Stack: ItemStack;
}

declare type ItemStack = {
    NetworkID: number;
    MetadataValue: number;
    BlockRuntimeID: number;
    Count: number;
    NBTData: {[k: string]: any};
    CanBePlacedOn: Array<string>;
    CanBreak: Array<string>;
    HasNetworkID: boolean;
}

declare type ChunkPos = [number, number];



declare type EntityMetadata = {
    [k: EntityDataKey]: any;
    SetFlag: (key: EntityDataKey, index: EntityDataFlag) => void;
    Flag: (key: EntityDataKey, index: EntityDataFlag) => boolean;
};

declare enum EntityDataKey {
	Flags,
	StructuralIntegrity,
	Variant,
	ColorIndex,
	Name,
	Owner,
	Target,
	AirSupply,
	EffectColor,
	EffectAmbience,
	JumpDuration,
	Hurt,
	HurtDirection,
	RowTimeLeft,
	RowTimeRight,
	Value,
	DisplayTileRuntimeID,
	DisplayOffset,
	CustomDisplay,
	Swell,
	OldSwell,
	SwellDirection,
	ChargeAmount,
	CarryBlockRuntimeID,
	ClientEvent,
	UsingItem,
	PlayerFlags,
	PlayerIndex,
	BedPosition,
	PowerX,
	PowerY,
	PowerZ,
	AuxPower,
	FishX,
	FishZ,
	FishAngle,
	AuxValueData,
	LeashHolder,
	Scale,
	HasNPC,
	NPCData,
	Actions,
	AirSupplyMax,
	MarkVariant,
	ContainerType,
	ContainerSize,
	ContainerStrengthModifier,
	BlockTarget,
	Inventory,
	TargetA,
	TargetB,
	TargetC,
	AerialAttack,
	Width,
	Height,
	FuseTime,
	SeatOffset,
	SeatLockPassengerRotation,
	SeatLockPassengerRotationDegrees,
	SeatRotationOffset,
	SeatRotationOffstDegrees,
	DataRadius,
	DataWaiting,
	DataParticle,
	PeekID,
	AttachFace,
	Attached,
	AttachedPosition,
	TradeTarget,
	Career,
	HasCommandBlock,
	CommandName,
	LastCommandOutput,
	TrackCommandOutput,
	ControllingSeatIndex,
	Strength,
	StrengthMax,
	DataSpellCastingColor,
	DataLifetimeTicks,
	PoseIndex,
	DataTickOffset,
	AlwaysShowNameTag,
	ColorTwoIndex,
	NameAuthor,
	Score,
	BalloonAnchor,
	PuffedState,
	BubbleTime,
	Agent,
	SittingAmount,
	SittingAmountPrevious,
	EatingCounter,
	FlagsTwo,
	LayingAmount,
	LayingAmountPrevious,
	DataDuration,
	DataSpawnTime,
	DataChangeRate,
	DataChangeOnPickup,
	DataPickupCount,
	InteractText,
	TradeTier,
	MaxTradeTier,
	TradeExperience,
	SkinID,
	SpawningFrames,
	CommandBlockTickDelay,
	CommandBlockExecuteOnFirstTick,
	AmbientSoundInterval,
	AmbientSoundIntervalRange,
	AmbientSoundEventName,
	FallDamageMultiplier,
	NameRawText,
	CanRideTarget,
	LowTierCuredTradeDiscount,
	HighTierCuredTradeDiscount,
	NearbyCuredTradeDiscount,
	NearbyCuredDiscountTimeStamp,
	HitBox,
	IsBuoyant,
	FreezingEffectStrength,
	BuoyancyData,
	GoatHornCount,
	BaseRuntimeID,
	MovementSoundDistanceOffset,
	HeartbeatIntervalTicks,
	HeartbeatSoundEvent,
	PlayerLastDeathPosition,
	PlayerLastDeathDimension,
	PlayerHasDied,
	CollisionBox,
};

declare enum EntityDataFlag {
    OnFire,
	Sneaking,
	Riding,
	Sprinting,
	UsingItem,
	Invisible,
	Tempted,
	InLove,
	Saddled,
	Powered,
	Ignited,
	Baby,
	Converting,
	Critical,
	ShowName,
	AlwaysShowName,
	NoAI,
	Silent,
	WallClimbing,
	Climb,
	Swim,
	Fly,
	Walk,
	Resting,
	Sitting,
	Angry,
	Interested,
	Charged,
	Tamed,
	Orphaned,
	Leashed,
	Sheared,
	Gliding,
	Elder,
	Moving,
	Breathing,
	Chested,
	Stackable,
	ShowBottom,
	Standing,
	Shaking,
	Idling,
	Casting,
	Charging,
	KeyboardControlled,
	PowerJump,
	Dash,
	Lingering,
	HasCollision,
	HasGravity,
	FireImmune,
	Dancing,
	Enchanted,
	ReturnTrident,
	ContainerPrivate,
	Transforming,
	DamageNearbyMobs,
	Swimming,
	Bribed,
	Pregnant,
	LayingEgg,
	PassengerCanPick,
	TransitionSitting,
	Eating,
	LayingDown,
	Sneezing,
	Trusting,
	Rolling,
	Scared,
	InScaffolding,
	OverScaffolding,
	DescendThroughBlock,
	Blocking,
	TransitionBlocking,
	BlockedUsingShield,
	BlockedUsingDamagedShield,
	Sleeping,
	WantsToWake,
	TradeInterest,
	DoorBreaker,
	BreakingObstruction,
	DoorOpener,
	Captain,
	Stunned,
	Roaring,
	DelayedAttack,
	AvoidingMobs,
	AvoidingBlock,
	FacingTargetToRangeAttack,
	HiddenWhenInvisible,
	InUI,
	Stalking,
	Emoting,
	Celebrating,
	Admiring,
	CelebratingSpecial,
	OutOfControl,
	RamAttack,
	PlayingDead,
	InAscendingBlock,
	OverDescendingBlock,
	Croaking,
	DigestMob,
	JumpGoal,
	Emerging,
	Sniffing,
	Digging,
	SonicBoom,
	HasDashTimeout,
	PushTowardsClosestSpace,
	Scenting,
	Rising,
	FeelingHappy,
	Searching,
	Crawling,
}
